### ISSUE TITLE
Latest package breakes Scenes

### ISSUE THREAD

**Issue by niels9001** [Q42/Q42.HueApi#50]
Just a heads up - after installing the latest NuGet package scenes are no longer cast correctly. Stuff like id is null.

**Comment by michielpost** [comment]
Thanks. It's fixed in version 2.2.2 which is now on NuGet.
It was caused by removed a bit too much fields with this change: https://github.com/Q42/Q42.HueApi/issues/49

**Comment by SyedWasiHaider** [comment]
Hi there. This may not be related to the above bug but I found that when I add a scene using the hue dashboard (https://my.meethue.com/en-us/my-scenes), the REST API endpoint /scenes/ will still not include those. Is there any way to get those scenes?

**Comment by michielpost** [comment]
They are probably only stored on the Philips Hue servers, so the bridge does not have them locally stored.
